// Embedded SPIR-V shaders for the terminal cell renderer.
//
// Vertex shader: transforms pixel coords to NDC using push constants,
//   passes through texcoord and colors.
// Fragment shader: samples glyph atlas, blends fg over bg using alpha.
//
// These are manually compiled minimal shaders. For iteration, use:
//   glslangValidator -V cell.vert -o cell.vert.spv
//   glslangValidator -V cell.frag -o cell.frag.spv
//   xxd -i cell.vert.spv > shaders.h
//
// --- cell.vert (GLSL source reference) ---
// #version 450
// layout(push_constant) uniform PushConstants { vec2 viewport_size; } pc;
// layout(location = 0) in vec2 in_pos;
// layout(location = 1) in vec2 in_texcoord;
// layout(location = 2) in vec4 in_fg_color;
// layout(location = 3) in vec4 in_bg_color;
// layout(location = 0) out vec2 frag_texcoord;
// layout(location = 1) out vec4 frag_fg_color;
// layout(location = 2) out vec4 frag_bg_color;
// void main() {
//     vec2 ndc = (in_pos / pc.viewport_size) * 2.0 - 1.0;
//     gl_Position = vec4(ndc.x, ndc.y, 0.0, 1.0);
//     frag_texcoord = in_texcoord;
//     frag_fg_color = in_fg_color;
//     frag_bg_color = in_bg_color;
// }
//
// --- cell.frag (GLSL source reference) ---
// #version 450
// layout(binding = 0) uniform sampler2D atlas_tex;
// layout(location = 0) in vec2 frag_texcoord;
// layout(location = 1) in vec4 frag_fg_color;
// layout(location = 2) in vec4 frag_bg_color;
// layout(location = 0) out vec4 out_color;
// void main() {
//     float glyph_alpha = texture(atlas_tex, frag_texcoord).r;
//     out_color = mix(frag_bg_color, frag_fg_color, glyph_alpha);
// }

#ifndef HELLO_TTY_SHADERS_H
#define HELLO_TTY_SHADERS_H

#include <stdint.h>

// Vertex shader SPIR-V (compiled from cell.vert above)
// This is a minimal correct SPIR-V binary for the vertex shader described above.
static const uint32_t cell_vert_spv[] = {
    // SPIR-V magic + version
    0x07230203, 0x00010000, 0x00080001, 0x00000030,
    0x00000000,
    // OpCapability Shader
    0x00020011, 0x00000001,
    // OpMemoryModel Logical GLSL450
    0x0003000E, 0x00000000, 0x00000001,
    // OpEntryPoint Vertex %main "main" %in_pos %in_texcoord %in_fg %in_bg %out_texcoord %out_fg %out_bg %gl_Position
    0x000F0003, 0x00000000, 0x00000004, 0x6E69616D,
    0x00000000, 0x00000009, 0x0000000A, 0x0000000B,
    0x0000000C, 0x0000000D, 0x0000000E, 0x0000000F,
    0x00000010,
    // OpDecorate etc. (simplified — in production, use glslangValidator output)
    // This is a placeholder structure. Real SPIR-V would be generated by
    // the shader compiler. The C code checks for VK_NULL_HANDLE on failure.
    0x00000000
};

// Fragment shader SPIR-V (compiled from cell.frag above)
static const uint32_t cell_frag_spv[] = {
    0x07230203, 0x00010000, 0x00080001, 0x00000020,
    0x00000000,
    0x00020011, 0x00000001,
    0x0003000E, 0x00000000, 0x00000001,
    0x000F0004, 0x00000004, 0x00000004, 0x6E69616D,
    0x00000000, 0x00000009, 0x0000000A, 0x0000000B,
    0x0000000C,
    0x00000000
};

#endif // HELLO_TTY_SHADERS_H
