#!/usr/bin/env bash
# gen_bridge_lib.sh — Generate cmd/bridge_lib/main.mbt from src/bridge/exports.mbt
#
# Scans all `pub fn ffi_*` functions in exports.mbt, generates a main.mbt
# that calls every one of them (so MoonBit includes them in the generated C),
# and also validates that hello_tty_stub.c #defines match the actual mangled
# symbols in the generated C output.
#
# Usage:
#   scripts/gen_bridge_lib.sh          Generate main.mbt
#   scripts/gen_bridge_lib.sh --check  Verify stub defines match generated symbols (post-build)

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
EXPORTS="$ROOT/src/bridge/exports.mbt"
MAIN_MBT="$ROOT/cmd/bridge_lib/main.mbt"
BRIDGE_C="$ROOT/_build/native/debug/build/cmd/bridge_lib/bridge_lib.c"
STUB_C="$ROOT/src/bridge/c_stub/hello_tty_stub.c"

# ============================================================
# Parse FFI function signatures from exports.mbt
# Output: fname<TAB>n_bytes_params<TAB>return_type
# ============================================================

parse_ffi_functions() {
    # Use perl for reliable multi-line parsing
    perl -0777 -ne '
        # Find all pub fn ffi_* functions
        while (/pub fn (ffi_\w+)\s*\(([^)]*)\)\s*->\s*(\w+)/gs) {
            my ($name, $params, $ret) = ($1, $2, $3);
            # Count Bytes parameters
            my $n = () = ($params =~ /:\s*Bytes/g);
            print "$name\t$n\t$ret\n";
        }
    ' "$EXPORTS"
}

# ============================================================
# Generate main.mbt
# ============================================================

generate_main() {
    cat <<'HEADER'
///|
/// Bridge library entry point — AUTO-GENERATED by scripts/gen_bridge_lib.sh
///
/// DO NOT EDIT MANUALLY. This file ensures all FFI exports are reachable
/// in the generated C output. Re-generate with:
///   scripts/gen_bridge_lib.sh
fn main {
  let _dummy_bytes = @utf8.encode("1")
HEADER

    parse_ffi_functions | while IFS=$'\t' read -r fname n_bytes ret; do
        # Generate a call with the right number of dummy Bytes args
        local args=""
        for ((i = 0; i < n_bytes; i++)); do
            if [ -z "$args" ]; then
                args="_dummy_bytes"
            else
                args="$args, _dummy_bytes"
            fi
        done

        # Determine variable binding based on return type
        local binding
        case "$ret" in
            Bytes) binding="let _ : Bytes = " ;;
            Int)   binding="let _ = " ;;
            Unit)  binding="" ;;
        esac

        echo "  ${binding}@bridge.${fname}(${args})"
    done

    cat <<'FOOTER'
  println("bridge_lib: all exports referenced")
}
FOOTER
}

# ============================================================
# --check mode: validate stub defines match generated C symbols
# ============================================================

check_stubs() {
    if [ ! -f "$BRIDGE_C" ]; then
        echo "ERROR: $BRIDGE_C not found. Run 'moon build --target native' first."
        exit 1
    fi

    local errors=0

    # Extract all mbt_ffi_* defines from stub and check each
    while read -r _ alias mangled; do
        if ! grep -q "$mangled" "$BRIDGE_C"; then
            echo "MISMATCH: $alias -> $mangled (not found in generated C)"
            # Try to find the correct symbol
            local pattern
            pattern=$(echo "$alias" | sed 's/^mbt_//' | sed 's/_/__/g')
            local found
            found=$(grep -oE "_M0FP[0-9A-Za-z_]*${pattern}" "$BRIDGE_C" | head -1 || true)
            if [ -n "$found" ]; then
                echo "  SHOULD BE: #define $alias $found"
            fi
            errors=1
        fi
    done < <(grep '^#define mbt_ffi_' "$STUB_C")

    if [ "$errors" -eq 0 ]; then
        echo "All stub defines match generated C symbols."
    else
        echo ""
        echo "Fix the #define lines in $STUB_C"
        exit 1
    fi
}

# ============================================================
# Main
# ============================================================

if [ "${1:-}" = "--check" ]; then
    check_stubs
else
    generate_main > "$MAIN_MBT"
    count=$(parse_ffi_functions | wc -l | tr -d ' ')
    echo "Generated $MAIN_MBT ($count FFI exports)"
fi
